// Generated by https://quicktype.io

export type PromiseReturnType<T extends (...args: any[]) => any> =
  ReturnType<T> extends Promise<infer U> ? U : T;

// Generated by https://quicktype.io
export type CharacterComplete = {
  id: number;
  name: string;
  status: string;
  species: string;
  type: string;
  gender: string;
  origin: Location;
  location: Location;
  image: string;
  episode: Episode[];
  url: string;
  created: string;
};

// Generated by https://quicktype.io

export type Character = {
  id: number;
  name: string;
  status: string;
  species: string;
  type: string;
  gender: string;
  origin: { name: string; url: string };
  location: { name: string; url: string };
  image: string;
  episode: string[];
  url: string;
  created: string;
};

// Generated by https://quicktype.io
export type Location = {
  id: number;
  name: string;
  type: string;
  dimension: string;
  residents: string[];
  url: string;
  created: string;
};

// Generated by https://quicktype.io
export type Episode = {
  id: number;
  name: string;
  air_date: string;
  episode: string;
  characters: string[];
  url: string;
  created: string;
};

export type Response<Type> = {
  info: {
    count: number;
    next: null | string;
    pages: number;
    prev: null | string;
  };
  results: Type[];
};
